server:
  port: 9663
spring:
  application:
    name: spring-r2dbc
  profiles:
    active: dev
  r2dbc:
    url: r2dbc:postgres://livk.com:5432/spring_livk
    username: postgres
    password: 123456
