spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://livk.com:3306/livk_oauth
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath*:mapper/*.xml
rsa:
  key:
    private-key: classpath:id_key_rsa
    public-key: classpath:id_key_rsa.pub
server:
  port: 9987
