version: 2.1

executors:
  ubuntu:
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    machine:
      image: ubuntu-2204:2024.11.1
      docker_layer_caching: true
    resource_class: arm.large

jobs:
  jdk21-ci:
    executor: ubuntu
    steps:
      - run: sudo apt-get update
      - run: sudo apt install openjdk-21-jdk
      - checkout
      - run: ./gradlew build
  jdk22-ci:
    executor: ubuntu
    steps:
      - run: sudo apt-get update
      - run: sudo apt install openjdk-22-jdk
      - checkout
      - run: ./gradlew build
  jdk23-ci:
    docker:
      - image: cimg/openjdk:23.0.1
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run: ./gradlew build

workflows:
  gradle-build:
    jobs:
      - jdk21-ci
      - jdk22-ci
      - jdk23-ci
