version: 2.1

jobs:
  jdk21-ci:
    docker:
      - image: cimg/openjdk:21.0.5
      - image: gradle:latest

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - run: gradle dependencies
      - run: gradle build

  jdk22-ci:
    docker:
      - image: cimg/openjdk:22.0.2
      - image: gradle:latest

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - run: gradle dependencies
      - run: gradle build

workflows:
  gradle-build:
    jobs:
      - jdk21-ci
      - jdk22-ci
