spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 1
            client-secret: 2
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost/api/login/oauth2/github
            scope: user
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
