[versions]
springBoot = "3.0.2"
pagehelper = "5.3.2"
pagehelperBoot = "1.4.6"
oauth2Authorization = "1.0.0"
mybatis = "3.5.11"
springMybatis = "3.0.1"
guava = "31.1-jre"
easyExcel = "3.1.5"
javaWebSocket = "1.5.3"
redisson = "3.19.1"
zookeeper = "3.8.0"
clickhouseJdbc = "0.3.2-patch11"
pulsarClient = "2.11.0"
googleFindbugs = "3.0.1"
mapstruct = "1.5.3.Final"
mapstructLombok = "0.2.0"
curator = "5.4.0"
ip2region = "2.6.6"
asciidoctorJvm = "3.3.2"
browscapJava = "1.3.13"
autoService = "1.0.1"
yauaa = "7.10.0"
springdoc = "2.0.2"
googleJavase = "3.5.1"
springBootAdmin = "3.0.0-M9"
nimbusdsJwt = "9.28"
rocketStarter = "2.2.2"
jsqlparser = "4.5"
nexusStaging = "0.30.0"

[libraries]
spring-boot-admin-dependencies = { group = "de.codecentric", name = "spring-boot-admin-dependencies", version.ref = "springBootAdmin" }
pagehelper = { group = "com.github.pagehelper", name = "pagehelper", version.ref = "pagehelper" }
pagehelper-starter = { group = "com.github.pagehelper", name = "pagehelper-spring-boot-starter", version.ref = "pagehelperBoot" }
oauth2-authorization-server = { group = "org.springframework.security", name = "spring-security-oauth2-authorization-server", version.ref = "oauth2Authorization" }
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
easyexcel = { group = "com.alibaba", name = "easyexcel", version.ref = "easyExcel" }
mybatis-starter = { group = "org.mybatis.spring.boot", name = "mybatis-spring-boot-starter", version.ref = "springMybatis" }
mybatis-autoconfigure = { group = "org.mybatis.spring.boot", name = "mybatis-spring-boot-autoconfigure", version.ref = "springMybatis" }
mybatis-spring = { group = "org.mybatis", name = "mybatis-spring", version.ref = "springMybatis" }
mybatis = { group = "org.mybatis", name = "mybatis", version.ref = "mybatis" }
java-webSocket = { group = "org.java-websocket", name = "Java-WebSocket", version.ref = "javaWebSocket" }
redisson-starter = { group = "org.redisson", name = "redisson-spring-boot-starter", version.ref = "redisson" }
redisson = { group = "org.redisson", name = "redisson", version.ref = "redisson" }
zookeeper = { group = "org.apache.zookeeper", name = "zookeeper", version.ref = "zookeeper" }
clickhouse-jdbc = { group = "com.clickhouse", name = "clickhouse-jdbc", version.ref = "clickhouseJdbc" }
pulsar-client = { group = "org.apache.pulsar", name = "pulsar-client", version.ref = "pulsarClient" }
findbugs-annotations = { group = "com.google.code.findbugs", name = "annotations", version.ref = "googleFindbugs" }
mapstruct = { group = "org.mapstruct", name = "mapstruct", version.ref = "mapstruct" }
mapstruct-processor = { group = "org.mapstruct", name = "mapstruct-processor", version.ref = "mapstruct" }
lombok-mapstruct = { group = "org.projectlombok", name = "lombok-mapstruct-binding", version.ref = "mapstructLombok" }
curator-recipes = { group = "org.apache.curator", name = "curator-recipes", version.ref = "curator" }
ip2region = { group = "org.lionsoul", name = "ip2region", version.ref = "ip2region" }
browscap-java = { group = "com.blueconic", name = "browscap-java", version.ref = "browscapJava" }
auto-service = { group = "com.google.auto.service", name = "auto-service", version.ref = "autoService" }
yauaa = { group = "nl.basjes.parse.useragent", name = "yauaa", version.ref = "yauaa" }
springdoc-openapi-dependencies = { group = "org.springdoc", name = "springdoc-openapi", version.ref = "springdoc" }
google-javase = { group = "com.google.zxing", name = "javase", version.ref = "googleJavase" }
nimbus-jose-jwt = { group = "com.nimbusds", name = "nimbus-jose-jwt", version.ref = "nimbusdsJwt" }
rocketmq-boot-starter = { group = "org.apache.rocketmq", name = "rocketmq-spring-boot-starter", version.ref = "rocketStarter" }
jsqlparser = { group = "com.github.jsqlparser", name = "jsqlparser", version.ref = "jsqlparser" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
asciidoctor-jvm = { id = "org.asciidoctor.jvm.convert", version.ref = "asciidoctorJvm" }
